"""斗罗大陆文字游戏核心常量与内容目录汇总。"""

from .ambush import AMBUSH_CATALOG, ambush_by_key
from .bosses import BOSS_CATALOG, boss_by_key
from .daily_tasks import DAILY_TASK_CATALOG, task_by_key, tasks_for_metric
from .events import EVENT_CATALOG, roll_event
from .realm import (
    ACTION_TYPE_LABELS,
    BREAKTHROUGH_RULES,
    DEFAULT_ACTION_POINT_COSTS,
    DEFAULT_DAILY_ACTION_LIMITS,
    DEFAULT_REALM_THRESHOLDS,
    EQUIP_SLOT_WEAPON,
    REALM_BASE_POWER,
    REALM_MAX_RING_TIER,
    RING_SLOT_CAP,
    RING_TIERS,
    RING_TIER_BASE_STATS,
    SOUL_BONE_PARTS,
    SOUL_BONE_RARITY_POWER,
    TITLED_DOULUO_TITLES,
    WUHUN_QUALITY_POWER,
    WUHUN_SYSTEM_POWER,
    max_allowed_ring_tier,
    realm_index,
    realm_stages,
    ring_stats_for_year,
    ring_tier_of_year,
    tier_by_name,
    total_soul_power_needed,
)
from .sects import SECT_CATALOG, sect_by_key
from .soulbeast import HUNT_REGIONS, first_region_for_stage, region_by_key, regions_for_stage
from .soulbone import SOULBONE_CATALOG, random_soulbone_by_part, random_soulbone_by_rarity, soulbone_by_key
from .wuhun import WUHUN_CATALOG, random_wuhun, wuhun_by_key

__all__ = [
    "AMBUSH_CATALOG",
    "ambush_by_key",
    "BOSS_CATALOG",
    "boss_by_key",
    "DAILY_TASK_CATALOG",
    "task_by_key",
    "tasks_for_metric",
    "EVENT_CATALOG",
    "roll_event",
    "ACTION_TYPE_LABELS",
    "BREAKTHROUGH_RULES",
    "DEFAULT_ACTION_POINT_COSTS",
    "DEFAULT_DAILY_ACTION_LIMITS",
    "DEFAULT_REALM_THRESHOLDS",
    "EQUIP_SLOT_WEAPON",
    "REALM_BASE_POWER",
    "REALM_MAX_RING_TIER",
    "RING_SLOT_CAP",
    "RING_TIERS",
    "RING_TIER_BASE_STATS",
    "SOUL_BONE_PARTS",
    "SOUL_BONE_RARITY_POWER",
    "TITLED_DOULUO_TITLES",
    "WUHUN_QUALITY_POWER",
    "WUHUN_SYSTEM_POWER",
    "max_allowed_ring_tier",
    "realm_index",
    "realm_stages",
    "ring_stats_for_year",
    "ring_tier_of_year",
    "tier_by_name",
    "total_soul_power_needed",
    "SECT_CATALOG",
    "sect_by_key",
    "HUNT_REGIONS",
    "first_region_for_stage",
    "region_by_key",
    "regions_for_stage",
    "SOULBONE_CATALOG",
    "random_soulbone_by_part",
    "random_soulbone_by_rarity",
    "soulbone_by_key",
    "WUHUN_CATALOG",
    "random_wuhun",
    "wuhun_by_key",
]
