"""斗罗大陆内容目录(由设计内容包生成,数据驱动)。"""

from __future__ import annotations

import random
from typing import Any


SECT_CATALOG: list[dict[str, Any]] = [{'key': 'shrek_academy',
  'name': '史莱克学院',
  'description': '大陆最传奇的怪物学院，只收怪物不收普通人。以实战锤炼与团队情谊闻名，史莱克七怪在此崛起，唐三、戴沐白、小舞、奥斯卡等皆出于此。口号：不敢惹事是庸才。',
  'entry_coin': 1500,
  'salary_coin': 100,
  'bonus': {'attack': 30, 'defense': 30, 'speed': 30, 'spirit': 30},
  'positions': [{'key': 'disciple', 'name': '弟子', 'required_contribution': 0},
                {'key': 'deacon', 'name': '执事', 'required_contribution': 200},
                {'key': 'elder', 'name': '长老', 'required_contribution': 800},
                {'key': 'vice_master', 'name': '副宗主', 'required_contribution': 2000},
                {'key': 'master', 'name': '宗主', 'required_contribution': 5000}]},
 {'key': 'wuhun_hall',
  'name': '武魂殿',
  'description': '大陆第一势力，掌控无数分殿与魂师资源，教皇比比东统领，下设斗罗殿、猎魂殿。以振兴武魂、追求封号与神位为宗旨，爪牙遍布大陆每一座城池。',
  'entry_coin': 9000,
  'salary_coin': 600,
  'bonus': {'attack': 45, 'defense': 35, 'speed': 40, 'spirit': 60},
  'positions': [{'key': 'disciple', 'name': '弟子', 'required_contribution': 0},
                {'key': 'deacon', 'name': '执事', 'required_contribution': 500},
                {'key': 'elder', 'name': '长老', 'required_contribution': 2000},
                {'key': 'vice_master', 'name': '副宗主', 'required_contribution': 4500},
                {'key': 'master', 'name': '宗主', 'required_contribution': 10000}]},
 {'key': 'tiandou_royal_academy',
  'name': '天斗皇家学院',
  'description': '天斗帝国皇室创办的顶级魂师学院，坐落于天斗城。师资雄厚、藏书万卷，以正统教育与仪礼风度见长，秦明等名师在此执教。',
  'entry_coin': 4000,
  'salary_coin': 200,
  'bonus': {'attack': 25, 'defense': 25, 'speed': 25, 'spirit': 45},
  'positions': [{'key': 'disciple', 'name': '弟子', 'required_contribution': 0},
                {'key': 'deacon', 'name': '执事', 'required_contribution': 300},
                {'key': 'elder', 'name': '长老', 'required_contribution': 1200},
                {'key': 'vice_master', 'name': '副宗主', 'required_contribution': 3000},
                {'key': 'master', 'name': '宗主', 'required_contribution': 7000}]},
 {'key': 'blue_lightning_dragon_clan',
  'name': '蓝电霸王龙宗',
  'description': '上三宗之一，传承天下第一兽武魂蓝电霸王龙。宗规森严，血脉霸烈，攻伐凌厉，同阶魂师之中攻击力冠绝群伦。',
  'entry_coin': 7000,
  'salary_coin': 400,
  'bonus': {'attack': 60, 'defense': 45, 'speed': 25, 'spirit': 15},
  'positions': [{'key': 'disciple', 'name': '弟子', 'required_contribution': 0},
                {'key': 'deacon', 'name': '执事', 'required_contribution': 400},
                {'key': 'elder', 'name': '长老', 'required_contribution': 1500},
                {'key': 'vice_master', 'name': '副宗主', 'required_contribution': 3500},
                {'key': 'master', 'name': '宗主', 'required_contribution': 8000}]},
 {'key': 'haotian_sect',
  'name': '昊天宗',
  'description': '上三宗之首，天下第一器武魂昊天锤之宗。以昊天九绝与力量撼山闻名，行事刚烈、护短成性。昊天斗罗唐昊曾凭一柄昊天锤名震大陆。',
  'entry_coin': 12000,
  'salary_coin': 700,
  'bonus': {'attack': 75, 'defense': 55, 'speed': 20, 'spirit': 30},
  'positions': [{'key': 'disciple', 'name': '弟子', 'required_contribution': 0},
                {'key': 'deacon', 'name': '执事', 'required_contribution': 500},
                {'key': 'elder', 'name': '长老', 'required_contribution': 2000},
                {'key': 'vice_master', 'name': '副宗主', 'required_contribution': 5000},
                {'key': 'master', 'name': '宗主', 'required_contribution': 12000}]},
 {'key': 'xiangjia_sect',
  'name': '象甲宗',
  'description': '下四宗之一，传承大力金刚象武魂，宗主呼延震。门下弟子皮糙肉厚、力大无穷，防御冠绝各宗，一身横练可比魂骨。',
  'entry_coin': 2500,
  'salary_coin': 150,
  'bonus': {'attack': 35, 'defense': 70, 'speed': 10, 'spirit': 10},
  'positions': [{'key': 'disciple', 'name': '弟子', 'required_contribution': 0},
                {'key': 'deacon', 'name': '执事', 'required_contribution': 250},
                {'key': 'elder', 'name': '长老', 'required_contribution': 1000},
                {'key': 'vice_master', 'name': '副宗主', 'required_contribution': 2500},
                {'key': 'master', 'name': '宗主', 'required_contribution': 6000}]},
 {'key': 'seven_treasure_sect',
  'name': '七宝琉璃宗',
  'description': '上三宗之一，天下第一辅助宗门，传承辅助至宝七宝琉璃塔（九宝琉璃塔）。财力雄厚，更有剑斗罗尘心与骨斗罗古榕两位封号斗罗镇守，是大陆辅助系魂师的梦想归属。',
  'entry_coin': 9000,
  'salary_coin': 500,
  'bonus': {'attack': 20, 'defense': 25, 'speed': 25, 'spirit': 80},
  'positions': [{'key': 'disciple', 'name': '弟子', 'required_contribution': 0},
                {'key': 'deacon', 'name': '执事', 'required_contribution': 400},
                {'key': 'elder', 'name': '长老', 'required_contribution': 1600},
                {'key': 'vice_master', 'name': '副宗主', 'required_contribution': 3800},
                {'key': 'master', 'name': '宗主', 'required_contribution': 8500}]}]

def sect_by_key(key: str) -> dict[str, Any] | None:
    for sect in SECT_CATALOG:
        if sect["key"] == str(key or ""):
            return sect
    return None
